baseURL = "https://adritian-demo.vercel.app/"
title = "Adritian Demo"
languageCode = "en"

[markup.goldmark.renderer]
unsafe = true

[module]
[[module.imports]]
path = "github.com/zetxek/adritian-free-hugo-theme"

## Base mounts - so your site's assets are available
[[module.mounts]]
source = "archetypes"
target = "archetypes"

[[module.mounts]]
source = "assets"
target = "assets"

[[module.mounts]]
source = "i18n"
target = "i18n"

[[module.mounts]]
source = "layouts"
target = "layouts"

[[module.mounts]]
source = "static"
target = "static"

# The following mounts are required for the theme to be able to load bootstrap
# Remember also to copy the theme's `package.json` to your site, and run `npm install`
[[module.mounts]]
source = "node_modules/bootstrap/scss"
target = "assets/scss/bootstrap"

[[module.mounts]]
source = "node_modules/bootstrap/dist/js"
target = "assets/js/bootstrap"

[[module.mounts]]
source = "node_modules/bootstrap/dist/js/bootstrap.bundle.min.js"
target = "assets/js/vendor/bootstrap.bundle.min.js"

[[module.mounts]]
source = "node_modules/bootstrap-print-css/css/bootstrap-print.css"
target = "assets/css/bootstrap-print.css"


[params]
title = 'Adritian - a high performance hugo theme by Adrián Moreno'
description = 'This hugo theme (Adritian) is based on Bootstrap and has features that make it suitable for a personal site, a portfolio or other kind of Single Page Applications.'
images = ['/img/og-img.png']
sections = [
  "showcase",
  "about",
  "education",
  "experience",
  "client-and-work",
  "testimonial",
  "contact",
  "newsletter",
]
# If you want to display an image logo in the header, you can add it here
# logo = '/img/hugo.svg'

homepageExperienceCount = 6

[params.analytics]
## Analytics parameters.
### Supported so far: Vercel (Page Insights, Analytics)
### And Google (Tag Manager, Analytics)

# controls vercel page insights - disabled by default
# to enable, just set to true
vercelPageInsights = false
vercelAnalytics = false

# google analytics and tag manager. to enable, set "enabled" to true
# and add the tracking code (UA-something for analytics, GTM-something for tag manager)
[params.analytics.googleAnalytics]
code = "UA-XXXXX-Y"
enabled = false
[params.analytics.googleTagManager]
code = "GTM-XXXXX"
enabled = false

[build]
[build.buildStats]
disableClasses = false
disableIDs = false
disableTags = false
enable = true

[params.languages.selector.disable]
footer = false
header = false
mobileHeader = false

[languages]
[languages.en]
disabled = false
languageCode = 'en'
languageDirection = 'ltr'
languageName = 'English'
title = ''
weight = 0

[languages.en.menus]
[[languages.en.menus.header]]
name = 'About'
URL = '#about'
weight = 2
[[languages.en.menus.header]]
name = 'Portfolio'
URL = '#portfolio'
weight = 3
#  [[languages.en.menus.header]]
#  name = "Experience"
#  URL = "#experience"
#  weight = 4

[[languages.en.menus.header]]
name = "How to"
URL = "/blog"
weight = 5

[[languages.en.menus.header]]
name = "Contact"
URL = "#contact"
weight = 6

[[languages.en.menus.footer]]
name = "About"
URL = "#about"
weight = 2

[[languages.en.menus.footer]]
name = "Portfolio"
URL = "#portfolio"
weight = 3

[[languages.en.menus.footer]]
name = "Contact"
URL = "#contact"
weight = 4


[languages.es]
disabled = false
languageCode = 'es'
languageDirection = 'ltr'
languageName = 'Español'
title = ''
weight = 0
[[languages.es.menus.header]]
name = 'Sobre mi'
URL = '/es/#about'
weight = 2
[[languages.es.menus.header]]
name = 'Portfolio'
URL = '/es/#portfolio'
weight = 3

#  [[languages.es.menus.header]]
#  name = "Experiencia"
#  URL = "/es/#experience"
#  weight = 4

[[languages.es.menus.header]]
name = "Blog"
URL = "/es/blog"
weight = 5

[[languages.es.menus.header]]
name = "Contacto"
URL = "/es/#contact"
weight = 6

[[languages.es.menus.footer]]
name = "Sobre mi"
URL = "/es/#about"
weight = 2

[[languages.es.menus.footer]]
name = "Portfolio"
URL = "/es/#portfolio"
weight = 3

[[languages.es.menus.footer]]
name = "Contact"
URL = "/es/#contact"
weight = 4

[languages.fr]
disabled = false
languageCode = 'fr'
languageDirection = 'ltr'
languageName = 'Français'
title = ''
weight = 0

[languages.fr.menus]
[[languages.fr.menus.header]]
name = 'About'
URL = '#about'
weight = 2
[[languages.fr.menus.header]]
name = 'Portfolio'
URL = '#portfolio'
weight = 3
#  [[languages.fr.menus.header]]
#  name = "Experience"
#  URL = "#experience"
#  weight = 4

[[languages.fr.menus.header]]
name = "Blog"
URL = "/blog"
weight = 5

[[languages.fr.menus.header]]
name = "Contact"
URL = "#contact"
weight = 6

[[languages.fr.menus.footer]]
name = "About"
URL = "#about"
weight = 2

[[languages.fr.menus.footer]]
name = "Portfolio"
URL = "#portfolio"
weight = 3

[[languages.fr.menus.footer]]
name = "Contact"
URL = "#contact"
weight = 4


# Plugins
[params.plugins]

# CSS Plugins
[[params.plugins.css]]
URL = "css/custom.css"
[[params.plugins.css]]
URL = "css/adritian-icons.css"
## Print css
[[params.plugins.css]]
URL = "css/bootstrap-print.css"

# JS Plugins
[[params.plugins.js]]
URL = "js/rad-animations.js"
[[params.plugins.js]]
URL = "js/sticky-header.js"
[[params.plugins.js]]
URL = "js/library/fontfaceobserver.js"

# SCSS Plugins
[[params.plugins.scss]]
URL = "scss/adritian.scss"


# theme/color style 
[params.colorTheme]

## the following configuration would disable automatic theme selection
#  [params.colorTheme.auto]
#    disable = true
#  [params.colorTheme.forced]
#    theme = "dark"

## the following parameter will disable theme override in the footer
#  [params.colorTheme.selector.disable]
#  footer = true


[params.colorTheme.selector.disable]
footer = false
header = false
mobileHeader = false
## by default we allow override AND automatic selection

[params.blog]
layout = "default"     # options: default, sidebar
sidebarWidth = "25"    # percentage width of the sidebar
showCategories = true
showRecentPosts = true
recentPostCount = 5
listStyle = "summary"  # options: simple, summary


[params.experience]
showJobCard = true # Set to false to hide the job card
