# Adritian Free Hugo Theme

baseURL = "https://example.org/"
languageCode = "en-us"
title = "Adritian Free Hugo Theme"
theme = "adritian-free-hugo-theme"
themesDir = "../.."
enableEmoji = true
enableRobotsTXT = true

# Plugins
[params.plugins]
# CSS Plugins
[[params.plugins.css]]
URL = "css/custom.css"
[[params.plugins.css]]
URL = "css/adritian-icons.css"
## Print css
[[params.plugins.css]]
URL = "css/bootstrap-print.css"
# JS Plugins
[[params.plugins.js]]
URL = "js/rad-animations.js"
[[params.plugins.js]]
URL = "js/sticky-header.js"
[[params.plugins.js]]
URL = "js/library/fontfaceobserver.js"
# SCSS Plugins
[[params.plugins.scss]]
URL = "scss/adritian.scss"

# Theme/color style 
[params.colorTheme]
## the following configuration would disable automatic theme selection
#  [params.colorTheme.auto]
#    disable = true
#  [params.colorTheme.forced]
#    theme = "dark"
## the following parameter will disable theme override in the footer
#  [params.colorTheme.selector.disable]
#  footer = true
[params.colorTheme.selector.disable]
footer = false
header = false
mobileHeader = false
## by default we allow override AND automatic selection

# Page transition settings
[params.pageTransition]
enabled = true  # Set to false to disable the page fade transition effect

[params.blog]
layout = "sidebar-right"     # options: default (no sidebar), sidebar, sidebar-right
sidebarWidth = "25"    # percentage width of the sidebar
showCategories = true
showRecentPosts = true
recentPostCount = 5
listStyle = "summary"  # options: simple, summary
featured_sort_by_weight = true
featured_sort_by_date = false

[params.experience]
showJobCard = true # Set to false to hide the job card

# and add the tracking code (UA-something for analytics, GTM-something for tag manager)
[params.analytics.googleAnalytics]
code = "UA-XXXXX-Y"
enabled = false
[params.analytics.googleTagManager]
code = "GTM-XXXXX"
enabled = false

[build]
writeStats = true
[build.buildStats]
enabledFor = ["scss"]
disableClasses = false
disableIDs = false
disableTags = false
enable = true

[params.languages.selector.disable]
footer = false
header = false
mobileHeader = false

[languages]
[languages.en]
disabled = false
languageCode = 'en'
languageDirection = 'ltr'
languageName = 'English'
title = ''
weight = 0
[languages.en.menus]
[[languages.en.menus.header]]
name = "Home"
URL = "/"
weight = 1
[[languages.en.menus.header]]
name = 'About'
URL = '#about'
weight = 2
[[languages.en.menus.header]]
name = 'Portfolio'
URL = '#portfolio'
weight = 3
[[languages.en.menus.header]]
name = 'Skills'
URL = '/skills'
weight = 4
[[languages.en.menus.header]]
name = "How to"
URL = "/blog"
weight = 5
[[languages.en.menus.header]]
pre = "email"
name = "email"
URL = "#contact"
weight = 6
[[languages.en.menus.header]]
pre = "search"
name = "Search"
URL = "/search"
weight = 7
[[languages.en.menus.footer]]
name = "Home"
URL = "/"
weight = 1
[[languages.en.menus.footer]]
name = "About"
URL = "#about"
weight = 2
[[languages.en.menus.footer]]
name = "Portfolio"
URL = "#portfolio"
weight = 3
[[languages.en.menus.footer]]
name = "Skills"
URL = "/skills"
weight = 4
[[languages.en.menus.footer]]
name = "Contact"
URL = "#contact"
weight = 5

[languages.es]
disabled = false
languageCode = 'es'
languageDirection = 'ltr'
languageName = 'Español'
title = ''
weight = 0
[[languages.es.menus.header]]
name = "INICIO"
URL = "/es/"
weight = 1
[[languages.es.menus.header]]
name = 'Sobre mi'
URL = '/es/#sobre-mi'
weight = 2
[[languages.es.menus.header]]
name = 'Trabajo'
URL = '/es/#trabajo'
weight = 3
[[languages.es.menus.header]]
name = 'Habilidades'
URL = '/es/skills'
weight = 4
[[languages.es.menus.header]]
name = "Blog"
URL = "/es/blog"
weight = 5
[[languages.es.menus.header]]
pre = "email"
name = "Contacto"
URL = "/es/#contacto"
weight = 6
[[languages.es.menus.header]]
pre = "search"
name = "Buscar"
URL = "/search"
weight = 7
[[languages.es.menus.footer]]
name = "INICIO"
URL = "/"
weight = 1
[[languages.es.menus.footer]]
name = "Sobre mi"
URL = "/es/#about"
weight = 2
[[languages.es.menus.footer]]
name = "Portfolio"
URL = "/es/#portfolio"
weight = 3
[[languages.es.menus.footer]]
name = "Habilidades"
URL = "/es/skills"
weight = 4
[[languages.es.menus.footer]]
name = "Contact"
URL = "/es/#contact"
weight = 5

[languages.fr]
disabled = false
languageCode = 'fr'
languageDirection = 'ltr'
languageName = 'Français'
title = ''
weight = 0
[languages.fr.menus]
[[languages.fr.menus.header]]
name = "ACCUEIL"
URL = "/fr/"
weight = 1
[[languages.fr.menus.header]]
name = 'About'
URL = '#about'
weight = 2
[[languages.fr.menus.header]]
name = 'Portfolio'
URL = '#portfolio'
weight = 3
[[languages.fr.menus.header]]
name = 'Compétences'
URL = '/fr/skills'
weight = 4
[[languages.fr.menus.header]]
name = "Blog"
URL = "/blog"
weight = 5
[[languages.fr.menus.header]]
pre = "email"
name = "Contact"
URL = "#contact"
weight = 6
[[languages.fr.menus.header]]
pre = "search"
name = "Recherche"
URL = "/search"
weight = 7
[[languages.fr.menus.footer]]
name = "ACCUEIL"
URL = "/fr/"
weight = 1
[[languages.fr.menus.footer]]
name = "About"
URL = "#about"
weight = 2
[[languages.fr.menus.footer]]
name = "Portfolio"
URL = "#portfolio"
weight = 3
[[languages.fr.menus.footer]]
name = "Compétences"
URL = "/fr/skills"
weight = 4
[[languages.fr.menus.footer]]
name = "Contact"
URL = "#contact"
weight = 5
