# Workflow to verify that the exampleSite runs ok
name: Verify example site

on:
    # Runs on pull requests targeting the default branch
    pull_request:
        branches: ["main"]
  
    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    env:
      HUGO_VERSION: 0.136.2
    steps:
      - name: Install Hugo CLI
        run: |
          wget -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.deb \
          && sudo dpkg -i ${{ runner.temp }}/hugo.deb
      
      - name: Setup hugo site
        run: hugo new site theme-test

      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          path: theme-test/themes/adritian-free-hugo-theme

      - name: Run demo site
        run: |
         cd theme-test
         npm i -D postcss postcss-cli autoprefixer
         cd themes/adritian-free-hugo-theme/exampleSite
         ## run example site
         hugo build --themesDir ../..