name: Test Module Init & HTML Validation

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]

jobs:
    test-module-init:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Setup Hugo
              uses: peaceiris/actions-hugo@v3
              with:
                hugo-version: 'latest'
                extended: true

            - name: Create test site
              run: |
                  hugo new site test-site
                  cd test-site
                    
            - name: Initialize Hugo module
              working-directory: ./test-site
              run: |
                    hugo mod init github.com/zetxek/test-site
                    hugo mod get -u github.com/zetxek/adritian-free-hugo-theme

            - name: Configure module ref
              if: github.ref != 'refs/heads/main'
              working-directory: ./test-site
              run: |
                # Use the branch that initiated the PR
                branch_name=${GITHUB_HEAD_REF}
                echo "Using branch: ${branch_name}"
                hugo mod get -u github.com/zetxek/adritian-free-hugo-theme@${branch_name}

            - name: Configure Hugo module in hugo.toml
              working-directory: ./test-site
              run: |
                echo '[module]
                [[module.imports]]
                path = "github.com/zetxek/adritian-free-hugo-theme"' > hugo.toml
            
            - name: Validate Hugo module configuration
              working-directory: ./test-site
              run: |
                hugo mod verify
                hugo mod graph
                
            
            - name: Upload test site
              uses: actions/upload-artifact@v4
              with:
                name: test-site
                path: test-site
                retention-days: 1

    build-site:
        needs: test-module-init
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            
            - name: Setup Hugo
              uses: peaceiris/actions-hugo@v3
              with:
                hugo-version: 'latest'
                extended: true
                
            - name: Download test site
              uses: actions/download-artifact@v4
              with:
                name: test-site
                path: test-site

            - name: Pack dependencies
              working-directory: ./test-site
              run: |
                    hugo mod npm pack

            - name: (debug) Cat package.json
              working-directory: ./test-site
              run: |
                    cat package.json

            - name: Npm install (bootstrap)
              working-directory: ./test-site
              run: |
                    npm install

            - name: (debug) ls node_modules
              working-directory: ./test-site
              run: |
                    ls node_modules

            - name: Run helper script (copy config and content)
              working-directory: ./test-site
              run: |
                    ./node_modules/@zetxek/adritian-theme-helper/dist/scripts/download-content.js

            - name: Run build
              working-directory: ./test-site
              run: hugo

            - name: Upload built site
              uses: actions/upload-artifact@v4
              with:
                name: built-site
                path: test-site/public
                retention-days: 1

    validate-html:
        needs: build-site
        runs-on: ubuntu-latest
        steps:
            - name: Download built site
              uses: actions/download-artifact@v4
              with:
                name: built-site
                path: ./public

            - name: Print index.html
              working-directory: ./public
              run: |
                    cat index.html

            # Validate HTML syntax with https://github.com/marketplace/actions/html5-validator
            - name: Validate HTML syntax
              uses: Cyb3r-Jak3/html5validator-action@v7.2.0
              with:
                root: ./public
                skip_git_check: true
