# Workflow to verify that the exampleSite runs ok
name: Verify example site

on:
    # Runs on pull requests targeting the default branch
    pull_request:
        branches: ["main"]
  
    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    env:
      HUGO_VERSION: 0.136.2
    steps:
      - name: Install Hugo CLI
        run: |
          wget -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.deb \
          && sudo dpkg -i ${{ runner.temp }}/hugo.deb
      
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Run demo site
        run: |
         ls
         mkdir tmp
         cd tmp
         hugo new site theme-test
         npm i -D postcss postcss-cli autoprefixer
         ## need to copy the theme to the site
         echo "first dir"
         ls -la ../ 
         echo "second dir"
         ls -lsa ../../
         cp -r ../../ themes/adritian-free-hugo-theme theme-test/themes/adritian-free-hugo-theme
         ## run example site
         hugo server --themesDir ../.. --theme adritian-free-hugo-theme --source ../../exampleSite --themesDir ../../exampleSite/themes --bind